### ISSUE TITLE
Contributing: npm install fails

### ISSUE THREAD

**Issue by richard-flosi** [vitalets/x-editable#665]
`npm install` fails which makes it hard to contribute.
Please update your dependencies accordingly.

```
x-editable $ npm install
npm http GET https://registry.npmjs.org/grunt-contrib-concat
npm http GET https://registry.npmjs.org/grunt-contrib-clean
npm http GET https://registry.npmjs.org/grunt-contrib-uglify
npm http GET https://registry.npmjs.org/grunt-contrib-qunit
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-contrib-requirejs
npm http GET https://registry.npmjs.org/grunt-contrib-jshint
npm http GET https://registry.npmjs.org/grunt-contrib-connect
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http 200 https://registry.npmjs.org/grunt-contrib-clean
npm http 200 https://registry.npmjs.org/grunt-contrib-concat
npm http 304 https://registry.npmjs.org/grunt-contrib-qunit
npm http 200 https://registry.npmjs.org/grunt-contrib-uglify
npm http 200 https://registry.npmjs.org/grunt-contrib-requirejs
npm http 200 https://registry.npmjs.org/grunt-contrib-connect
npm http 200 https://registry.npmjs.org/grunt
npm http 200 https://registry.npmjs.org/grunt-contrib-copy
npm WARN package.json grunt-contrib-connect@0.3.0 No README.md file found!
npm http 304 https://registry.npmjs.org/grunt-contrib-jshint
npm http GET https://registry.npmjs.org/requirejs
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/getobject
npm http GET https://registry.npmjs.org/exit
npm http GET https://registry.npmjs.org/grunt-legacy-util
npm http GET https://registry.npmjs.org/grunt-legacy-log
npm http GET https://registry.npmjs.org/grunt-lib-phantomjs
npm http GET https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/grunt-lib-contrib
npm http 200 https://registry.npmjs.org/requirejs
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/requirejs/-/requirejs-2.1.15.tgz
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/eventemitter2
npm http 200 https://registry.npmjs.org/colors
npm http 200 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/cli
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/console-browserify
npm http 304 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/requirejs/-/requirejs-2.1.15.tgz
npm http 304 https://registry.npmjs.org/nopt
npm http 200 https://registry.npmjs.org/hooker
npm http 200 https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/which
npm http 200 https://registry.npmjs.org/iconv-lite
npm http 200 https://registry.npmjs.org/getobject
npm http 200 https://registry.npmjs.org/connect
npm http 200 https://registry.npmjs.org/exit
npm http 200 https://registry.npmjs.org/grunt-legacy-util
npm http 200 https://registry.npmjs.org/grunt-legacy-log
npm http 200 https://registry.npmjs.org/underscore.string
npm http 200 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/grunt-lib-phantomjs
npm http 200 https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz
npm http 200 https://registry.npmjs.org/grunt-lib-contrib
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/console-browserify
npm http 304 https://registry.npmjs.org/cli
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/temporary
npm http GET https://registry.npmjs.org/phantomjs
npm http 200 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/temporary
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/phantomjs
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/zlib-browserify/0.0.1
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/adm-zip/0.4.4
npm http GET https://registry.npmjs.org/kew/0.4.0
npm http GET https://registry.npmjs.org/ncp/0.6.0
npm http GET https://registry.npmjs.org/npmconf/2.0.9
npm http GET https://registry.npmjs.org/mkdirp/0.5.0
npm http GET https://registry.npmjs.org/progress/1.1.8
npm http GET https://registry.npmjs.org/request/2.42.0
npm http GET https://registry.npmjs.org/request-progress/0.3.1
npm http GET https://registry.npmjs.org/package
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/zlib-browserify/0.0.1
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/zlib-browserify/-/zlib-browserify-0.0.1.tgz
npm http 304 https://registry.npmjs.org/npmconf/2.0.9
npm http 304 https://registry.npmjs.org/ncp/0.6.0
npm http 304 https://registry.npmjs.org/adm-zip/0.4.4
npm http 304 https://registry.npmjs.org/kew/0.4.0
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/mkdirp/0.5.0
npm http 304 https://registry.npmjs.org/progress/1.1.8
npm http 304 https://registry.npmjs.org/request/2.42.0
npm http 304 https://registry.npmjs.org/request-progress/0.3.1
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/package
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 200 https://registry.npmjs.org/zlib-browserify/-/zlib-browserify-0.0.1.tgz
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/throttleit
npm http 304 https://registry.npmjs.org/throttleit
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 200 https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/uid-number/0.0.5
npm http 200 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/send/0.1.1
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/cookie/0.0.5
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/osenv
npm ERR! Error: ENOENT, open '/Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/adm-zip/headers/index.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/Cellar/node/0.10.4/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/richard/OtherSites/x-editable
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/adm-zip/headers/index.js
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/config-chain
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/uid-number/0.0.5
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/mkdirp/node_modules/minimist'
npm ERR! error rolling back  phantomjs@1.9.10 { [Error: ENOTEMPTY, rmdir '/Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/mkdirp/node_modules/minimist']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/mkdirp/node_modules/minimist' }
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/once
npm http 200 https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/qs/-/qs-0.6.5.tgz
npm ERR! Error: ENOENT, open '/Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/mkdirp/node_modules/minimist/readme.markdown'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/Cellar/node/0.10.4/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/richard/OtherSites/x-editable
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/mkdirp/node_modules/minimist/readme.markdown
npm ERR! code ENOENT
npm ERR! errno 34
npm http 200 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/pause/0.0.1
npm http 200 https://registry.npmjs.org/fresh/0.1.0
npm http 200 https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http GET https://registry.npmjs.org/debug/-/debug-2.0.0.tgz
npm ERR! Error: No compatible version found: osenv@'^0.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.1.0"]
npm ERR!     at installTargetsError (/usr/local/Cellar/node/0.10.4/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/Cellar/node/0.10.4/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/Cellar/node/0.10.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/Cellar/node/0.10.4/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/richard/OtherSites/x-editable
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm http GET https://registry.npmjs.org/formidable/-/formidable-1.0.14.tgz
npm http 200 https://registry.npmjs.org/send/0.1.1
npm http 200 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/send/-/send-0.1.1.tgz
npm http GET https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm ERR! Error: ENOENT, lstat '/Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/request/CHANGELOG.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/Cellar/node/0.10.4/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/richard/OtherSites/x-editable
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR! path /Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/request/CHANGELOG.md
npm ERR! fstream_path /Users/richard/OtherSites/x-editable/node_modules/grunt-contrib-qunit/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/node_modules/request/CHANGELOG.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.4/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/source-map/0.1.34
npm http GET https://registry.npmjs.org/uglify-to-browserify
npm http 200 https://registry.npmjs.org/cookie/0.0.5
npm http 200 https://registry.npmjs.org/bytes/0.2.0
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http GET https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-0.6.5.tgz
npm http 200 https://registry.npmjs.org/pause/-/pause-0.0.1.tgz
npm http 200 https://registry.npmjs.org/send/-/send-0.1.1.tgz
npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.1.0.tgz
npm http 200 https://registry.npmjs.org/debug/-/debug-2.0.0.tgz
npm http 200 https://registry.npmjs.org/formidable/-/formidable-1.0.14.tgz
npm http 200 https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz
npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.0.5.tgz
npm http 200 https://registry.npmjs.org/bytes/-/bytes-0.2.0.tgz
npm http 200 https://registry.npmjs.org/uglify-to-browserify
npm http 200 https://registry.npmjs.org/source-map/0.1.34
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.34.tgz
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.34.tgz
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http 200 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
npm http GET https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm http 200 https://registry.npmjs.org/ms/-/ms-0.6.2.tgz
npm http 200 https://registry.npmjs.org/amdefine
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/richard/OtherSites/x-editable/npm-debug.log
npm ERR! not ok code 0
```

**Comment by nav12neo** [comment]
I am also facing the similar issue. What would be the reason and solution for this ?
