### ISSUE TITLE
html5 types test fails

### ISSUE THREAD

**Issue by tofutim** [vitalets/x-editable#830]
text: html5 types (2, 1, 3)Rerun36 ms
value correct
Died on test #2     at HTMLDocument.<anonymous> (http://127.0.0.1:8000/test/unit/text.js:485:4)
    at c (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:7857)
    at Object.p.add [as done] (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:8167)
    at b.fn.b.ready (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:2072)
    at b.fn.b.init (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:1602)
    at b (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:206)
    at http://127.0.0.1:8000/test/unit/text.js:1:1: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.
Source: 	
Error: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.
    at Error (native)
    at Object.$.fn.editableutils.setCursorPosition (http://127.0.0.1:8000/src/editable-form/editable-form-utils.js:26:22)
    at $.extend.activate (http://127.0.0.1:8000/src/inputs/text.js:38:40)
    at EditableForm.showForm (http://127.0.0.1:8000/src/editable-form/editable-form.js:163:28)
    at null.<anonymous> (http://127.0.0.1:8000/src/editable-form/editable-form.js:120:22)
    at b.isFunction.i (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:6336)
    at http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:9221
    at c (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:7857)
    at Object.p.add [as done] (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:8167)
    at Array.<anonymous> (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:9198)
Expected 40 assertions, but 2 were run
Source: 	
    at HTMLDocument.<anonymous> (http://127.0.0.1:8000/test/unit/text.js:485:4)
    at c (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:7857)
    at Object.p.add [as done] (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:8167)
    at b.fn.b.ready (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:2072)
    at b.fn.b.init (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:1602)
    at b (http://127.0.0.1:8000/test/libs/jquery/jquery-1.9.1.min.js:3:206)
    at http://127.0.0.1:8000/test/unit/text.js:1:1

**Comment by tofutim** [comment]
this is a problem in Chrome as the 'email' type is not selectable
