### ISSUE TITLE
popover closed nochange/manual not working in tests

### ISSUE THREAD

**Issue by tofutim** [vitalets/x-editable#834]
api: events: shown / hidden (reason: cancel, onblur, nochange, manual) (2, 13, 15)Rerun296 ms

1.popover closed nochangeSource:     at Anonymous function (http://localhost:8000/test/unit/api.js:143:14)
 

2.popover closed manualSource:     at Anonymous function (http://localhost:8000/test/unit/api.js:150:14)

**Comment by tofutim** [comment]
strict === checks that the types are the same, but the method value2str is deceptive because it doesn't actually change anything to a string... in inputs - 

       /**
        Converts value to string (for internal compare). For submitting to server used value2submit().

        @method value2str(value) 
        @param {mixed} value
        @returns {string}
       **/
       value2str: function(value) {
           return value;
       }, 

       /**
        Converts string received from server into value. Usually from `data-value` attribute.

        @method str2value(str)
        @param {string} str
        @returns {mixed}
       **/
       str2value: function(str) {
           return str;
       },

**Comment by tofutim** [comment]
changing value2str to return String(value) does work, but we will never be able to tell the difference between null and false
