### ISSUE TITLE
always sends `POST` on submit and ignores `ajaxOptions`

### ISSUE THREAD

**Issue by noise2** [vitalets/x-editable#997]
I have got following code-snap:

```JAVASCRIPT
$(this).editable({
  url: $(this).attr('data-url-x'),
  savenochange: true,
  ajaxOptions: { type: 'put' },
  params: function(params){ 
    params = $.extend(params, $(".value[data-pk='"+params.pk+"']").data('options'));
    delete params.pk;
    return params;
  },
}).editable('submit')
```
but the server will raise error:

```
Routing Error

No route matches [POST] "/x/y/1.json"

Rails.root: /home/dariush/Desktop/z

Framework Trace
actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
web-console (3.5.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.0) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.0) lib/web_console/middleware.rb:18:in `call'
```
It's supposed to send request as a `PUT` request not `POST`!!
A possible bug?

**Comment by Petercopter** [comment]
@noise2 The only way I got the plugin to use put was to use the defaults.
```
$.fn.editable.defaults.ajaxOptions = { type: 'put' };
```

**Comment by strausmann** [comment]
Any new information ?
